name: 'Setup IAM Bastion Role credentials'
description: 'Configures the credentials to access an IAM bastion role via the GitHub Token.'
author: 'idealo Internet GmbH'
inputs:
  token:
    required: false
    description: 'GitHub Token generated for this workflow'
    default: ${{ github.token }}
  endpoint:
    required: true
    description: 'The endpoint to use for exchanging the GitHub Token for AWS credentials'
  mode:
    required: false
    description: 'Which mode of credential setup should be used (env is more compatible, config creates config files that allow for auto-renewal)'
    default: 'env'
  role-to-assume:
    required: false
    description: 'Which AWS role should be assumed (only for config mode)'
  role-external-id:
    required: false
    description: 'The external ID of the role to assume (only for config mode)'
  ca-certificate:
    required: false
    description: 'Base64 encoded certificate authority chain that will be appehnded to the truststore when communicating via HTTPS.'
  client-certificate:
    required: false
    description: 'Base64 encoded client certificate the action uses to authenticate when mTLS is enabled.'
  client-key:
    required: false
    description: 'Base64 encoded client key the action uses to authenticate when mTLS is enabled.'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
