name: 'Setup IAM Bastion Role credentials'
description: 'Configures the credentials to access an IAM bastion role via the GitHub Token.'
author: 'idealo Internet GmbH'
inputs:
  token:
    required: false
    description: 'GitHub Token generated for this workflow'
    default: ${{ github.token }}
  endpoint:
    required: true
    description: 'The endpoint to use for exchanging the GitHub Token for AWS credentials'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
