name: 'CI'
on:
  push:
    branches:
      - main
      - '[0-9]+.x'

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-12.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-12.x
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Lint the code
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Create new release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag version series
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git tag -fa v${{ steps.semantic.outputs.new_release_major_version }} -m "Update v${{ steps.semantic.outputs.new_release_major_version }} tag"
          git push origin v${{ steps.semantic.outputs.new_release_major_version }} --force
